Repository bjjdestroyer/whats-cookin-starter-kit, pull requests merged in 2020-07, with the labels that each got.

#47 Feature/build recipe class and add ingredient class
  src/Ingredient.js
  src/Recipe.js
Labels: enhancement

#48 Add exports phrasing to ingredients data and Recipe, create GetIngred…
  data/ingredients.js
  src/Recipe.js
Labels: enhancement

#50 Feature/build recipe class
  src/Recipe.js
  src/Recipes.js
Labels: enhancement

#51 Add multiple tests for recipe and recipes - needs to be split #35
  test/recipe-test.js
Labels: documentation

#52 Feature/build recipes class
  src/Recipe.js
  src/Recipes.js
Labels: enhancement

#57 Feature/create user tests
  src/Recipe.js
  src/Recipes.js
  src/User.js
  test/recipe-test.js
  test/recipes-test.js
  test/user-test.js
Labels: refactor

#58 Feature/create user tests
  data/users.js
  src/Recipe.js
  test/user-test.js
Labels: documentation

#62 Feature/create pantry test
  test/pantry-test-js
  test/pantry-test.js
Labels: documentation

#63 Fix bug in User class and delete extra notes #30
  src/User.js
Labels: bug

#65 Tm test fixes
  test/recipe-test.js
  test/user-test.js
Labels: documentation

#66 Refactor recipe
  data/recipes.js
  src/Recipe.js
  test/recipe-test.js
Labels: documentation, refactor

#69 Make naming consistent
  src/Recipe.js
  src/Recipes.js
  test/recipes-test.js
  test/user-test.js
Labels: refactor

#70 Fix and test getIngredientNameList in Recipe.js
  src/Recipe.js
  test/recipe-test.js
Labels: enhancement

#72 Feature/recipe methods
  src/User.js
  test/recipe-test.js
  test/user-test.js
Labels: enhancement

#74 Pass canMakeRecipe in Pantry through its test
  src/Pantry.js
  test/pantry-test.js
Labels: enhancement

#78 Add sad path tests for pantry and recipe
  src/Pantry.js
  test/pantry-test.js
  test/recipe-test.js
  test/recipes-test.js
Labels: documentation

#80 Add test for pantry and pantry method test for user
  src/Recipes.js
  src/User.js
  test/pantry-test.js
  test/recipes-test.js
  test/user-test.js
Labels: documentation, enhancement

#82 Feature/scripts.js
  data/ingredients.js
  data/recipes.js
  data/users.js
  src/Pantry.js
  src/Recipe.js
  src/Recipes.js
  src/User.js
  src/index.html
  src/scripts.js
Labels: enhancement

#91 Lint Fixes
  src/Ingredient.js
  src/Pantry.js
  src/Recipe.js
  src/Recipes.js
  test/pantry-test.js
  test/recipe-test.js
  test/recipes-test.js
  test/user-test.js
Labels: refactor

#94 Refactor user class
  src/Pantry.js
  src/Recipe.js
  src/Recipes.js
  src/User.js
Labels: enhancement

#107 Make modal boxes
  src/User.js
  src/index.html
  src/scripts.js
  src/styles.css
Labels: enhancement

#115 Add units to listMissingIngredients user method
  src/Pantry.js
  src/Recipe.js
  src/User.js
Labels: Heavy-duty, enhancement

#117 Create List Displays for to cook, favorites, and shopping list
  src/index.html
  src/scripts.js
  src/styles.css
Labels: enhancement

#116 Get total price
  src/Recipe.js
Labels: enhancement

#118 Populate recipe cards
  src/User.js
  src/scripts.js
Labels: enhancement

#120 Add recipe ingredients to recipe card
  src/Recipe.js
  src/User.js
  src/scripts.js
Labels: enhancement

#123 Scripts test file
  src/scripts.js
  test/scripts-test.js
Labels: documentation

#125 Fix a bug in canMakeRecipe
  src/Pantry.js
  src/scripts.js
Labels: enhancement

#127 Change shopping button into icon
  src/index.html
  src/scripts.js
Labels: enhancement

#128 Add scrollbar to modal window
  src/styles.css
Labels: enhancement

#131 Take out comments and spaces
  src/Pantry.js
  src/Recipe.js
  src/Recipes.js
  src/scripts.js
Labels: refactor
